report-cooldown: 300

database:
  type: sqlite
  sqlite-file: reports.db
  mysql:
    host: localhost
    port: 3306
    database: netami_reports
    username: root
    password: ""
    
notifications:
  notify-admins: true
  play-sound: true
  notification-sound: ENTITY_EXPERIENCE_ORB_PICKUP

ui:
  enhanced-feedback: true
  auto-refresh: true

debug:
  enabled: false
  log-inventory-clicks: false
  log-chat-events: false